import { Candidate, Job, Client, Deal, Activity, Notification, AnalyticsData, AIInsight, User, Revenue, Expense, Invoice, RecruiterEarnings, FinancialStats } from './types';

export const currentUser: User = {
  id: 'u1',
  name: 'Sarah Chen',
  email: 'sarah@cgtrecruit.ai',
  avatar: '',
  role: 'admin',
  organizationId: 'org1',
  createdAt: '2024-01-15',
};

export const candidates: Candidate[] = [
  {
    id: 'c1',
    name: 'Alex Rivera',
    email: 'alex.r@email.com',
    phone: '+1 (555) 234-5678',
    avatar: '',
    title: 'Senior Full-Stack Engineer',
    location: 'San Francisco, CA',
    experience: 7,
    skills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'AWS', 'GraphQL'],
    aiScore: 94,
    source: 'LinkedIn',
    status: 'interview',
    salary: '₹180,000 - ₹220,000',
    appliedDate: '2024-03-15',
    jobId: 'j1',
    notes: ['Strong system design skills', 'Led team of 8 at previous company'],
    enrichment: {
      inferredSkills: ['Docker', 'CI/CD', 'Microservices'],
      predictedSeniority: 'Staff Engineer',
      skillMatchBreakdown: [
        { skill: 'React', match: 98 },
        { skill: 'Node.js', match: 95 },
        { skill: 'TypeScript', match: 92 },
        { skill: 'System Design', match: 88 },
        { skill: 'Leadership', match: 85 },
      ],
      missingSkills: ['Kubernetes', 'Terraform'],
      overallFit: 94,
    },
  },
  {
    id: 'c2',
    name: 'Priya Patel',
    email: 'priya.p@email.com',
    phone: '+1 (555) 345-6789',
    avatar: '',
    title: 'ML Engineer',
    location: 'New York, NY',
    experience: 5,
    skills: ['Python', 'TensorFlow', 'PyTorch', 'Kubernetes', 'SQL'],
    aiScore: 89,
    source: 'Referral',
    status: 'screening',
    salary: '₹160,000 - ₹200,000',
    appliedDate: '2024-03-18',
    jobId: 'j2',
    notes: ['Published 3 ML papers', 'Strong NLP background'],
    enrichment: {
      inferredSkills: ['MLOps', 'Data Engineering', 'Research'],
      predictedSeniority: 'Senior Engineer',
      skillMatchBreakdown: [
        { skill: 'Python', match: 97 },
        { skill: 'ML/AI', match: 95 },
        { skill: 'Deep Learning', match: 90 },
        { skill: 'MLOps', match: 78 },
      ],
      missingSkills: ['Go', 'Cloud Architecture'],
      overallFit: 89,
    },
  },
  {
    id: 'c3',
    name: 'Marcus Johnson',
    email: 'marcus.j@email.com',
    phone: '+1 (555) 456-7890',
    avatar: '',
    title: 'Product Designer',
    location: 'Austin, TX',
    experience: 6,
    skills: ['Figma', 'User Research', 'Prototyping', 'Design Systems', 'CSS'],
    aiScore: 87,
    source: 'Job Board',
    status: 'applied',
    salary: '₹140,000 - ₹170,000',
    appliedDate: '2024-03-20',
    jobId: 'j3',
    notes: ['Portfolio is impressive', 'Experience with B2B SaaS'],
    enrichment: {
      inferredSkills: ['Motion Design', 'Accessibility', 'Analytics'],
      predictedSeniority: 'Senior Designer',
      skillMatchBreakdown: [
        { skill: 'UI Design', match: 95 },
        { skill: 'User Research', match: 88 },
        { skill: 'Prototyping', match: 92 },
        { skill: 'Design Systems', match: 86 },
      ],
      missingSkills: ['Front-end Development', '3D Design'],
      overallFit: 87,
    },
  },
  {
    id: 'c4',
    name: 'Emma Watson',
    email: 'emma.w@email.com',
    phone: '+1 (555) 567-8901',
    avatar: '',
    title: 'DevOps Engineer',
    location: 'Seattle, WA',
    experience: 4,
    skills: ['AWS', 'Docker', 'Kubernetes', 'Terraform', 'Python'],
    aiScore: 82,
    source: 'LinkedIn',
    status: 'offer',
    salary: '₹150,000 - ₹180,000',
    appliedDate: '2024-03-10',
    jobId: 'j4',
    notes: ['AWS certified', 'Strong automation skills'],
    enrichment: {
      inferredSkills: ['CI/CD', 'Monitoring', 'Security'],
      predictedSeniority: 'Mid-Senior',
      skillMatchBreakdown: [
        { skill: 'AWS', match: 94 },
        { skill: 'Docker', match: 90 },
        { skill: 'K8s', match: 88 },
        { skill: 'IaC', match: 85 },
      ],
      missingSkills: ['GCP', 'Service Mesh'],
      overallFit: 82,
    },
  },
  {
    id: 'c5',
    name: 'James Liu',
    email: 'james.l@email.com',
    phone: '+1 (555) 678-9012',
    avatar: '',
    title: 'Backend Engineer',
    location: 'Chicago, IL',
    experience: 3,
    skills: ['Go', 'Rust', 'PostgreSQL', 'gRPC', 'Redis'],
    aiScore: 78,
    source: 'Career Page',
    status: 'applied',
    salary: '₹130,000 - ₹160,000',
    appliedDate: '2024-03-22',
    jobId: 'j1',
    notes: ['Open source contributor'],
    enrichment: {
      inferredSkills: ['Performance Optimization', 'Distributed Systems'],
      predictedSeniority: 'Mid-Level',
      skillMatchBreakdown: [
        { skill: 'Go', match: 92 },
        { skill: 'Databases', match: 85 },
        { skill: 'APIs', match: 80 },
      ],
      missingSkills: ['React', 'TypeScript', 'AWS'],
      overallFit: 78,
    },
  },
  {
    id: 'c6',
    name: 'Sofia Martinez',
    email: 'sofia.m@email.com',
    phone: '+1 (555) 789-0123',
    avatar: '',
    title: 'Data Scientist',
    location: 'Remote',
    experience: 5,
    skills: ['Python', 'R', 'SQL', 'Tableau', 'Spark'],
    aiScore: 91,
    source: 'Referral',
    status: 'hired',
    salary: '₹155,000 - ₹185,000',
    appliedDate: '2024-02-28',
    jobId: 'j5',
    notes: ['Excellent cultural fit', 'Started March 25'],
    enrichment: {
      inferredSkills: ['Statistics', 'A/B Testing', 'Data Viz'],
      predictedSeniority: 'Senior',
      skillMatchBreakdown: [
        { skill: 'Python', match: 96 },
        { skill: 'Statistics', match: 93 },
        { skill: 'ML', match: 88 },
        { skill: 'Communication', match: 90 },
      ],
      missingSkills: ['Deep Learning'],
      overallFit: 91,
    },
  },
  {
    id: 'c7',
    name: 'David Kim',
    email: 'david.k@email.com',
    phone: '+1 (555) 890-1234',
    avatar: '',
    title: 'Frontend Engineer',
    location: 'Los Angeles, CA',
    experience: 4,
    skills: ['React', 'Vue.js', 'TypeScript', 'CSS', 'Testing'],
    aiScore: 85,
    source: 'LinkedIn',
    status: 'screening',
    salary: '₹140,000 - ₹170,000',
    appliedDate: '2024-03-19',
    jobId: 'j1',
    notes: ['Great portfolio site'],
    enrichment: {
      inferredSkills: ['Animation', 'Performance', 'A11y'],
      predictedSeniority: 'Mid-Senior',
      skillMatchBreakdown: [
        { skill: 'React', match: 93 },
        { skill: 'TypeScript', match: 88 },
        { skill: 'CSS', match: 95 },
        { skill: 'Testing', match: 80 },
      ],
      missingSkills: ['Node.js', 'Database Design'],
      overallFit: 85,
    },
  },
  {
    id: 'c8',
    name: 'Rachel Green',
    email: 'rachel.g@email.com',
    phone: '+1 (555) 901-2345',
    avatar: '',
    title: 'Engineering Manager',
    location: 'Boston, MA',
    experience: 10,
    skills: ['Leadership', 'Agile', 'System Design', 'Java', 'Mentoring'],
    aiScore: 92,
    source: 'Headhunting',
    status: 'interview',
    salary: '₹200,000 - ₹250,000',
    appliedDate: '2024-03-12',
    jobId: 'j6',
    notes: ['Managed 30+ person org', 'Strong track record'],
    enrichment: {
      inferredSkills: ['Strategic Planning', 'Hiring', 'OKRs'],
      predictedSeniority: 'Director',
      skillMatchBreakdown: [
        { skill: 'Leadership', match: 97 },
        { skill: 'Strategy', match: 92 },
        { skill: 'Technical', match: 85 },
        { skill: 'Communication', match: 94 },
      ],
      missingSkills: [],
      overallFit: 92,
    },
  },
];

export const jobs: Job[] = [
  {
    id: 'j1',
    title: 'Senior Full-Stack Engineer',
    department: 'Engineering',
    location: 'San Francisco, CA',
    type: 'full-time',
    salary: '₹180K - ₹220K',
    description: 'Join our engineering team to build scalable web applications.',
    requirements: ['5+ years experience', 'React & Node.js', 'System Design', 'Team Leadership'],
    status: 'open',
    applicants: 24,
    postedDate: '2024-03-01',
    closingDate: '2024-04-15',
  },
  {
    id: 'j2',
    title: 'ML Engineer',
    department: 'AI/ML',
    location: 'New York, NY',
    type: 'full-time',
    salary: '₹160K - ₹200K',
    description: 'Build and deploy machine learning models at scale.',
    requirements: ['3+ years ML experience', 'Python/TensorFlow', 'MLOps', 'Research background'],
    status: 'open',
    applicants: 18,
    postedDate: '2024-03-05',
    closingDate: '2024-04-20',
  },
  {
    id: 'j3',
    title: 'Senior Product Designer',
    department: 'Design',
    location: 'Austin, TX',
    type: 'full-time',
    salary: '₹140K - ₹170K',
    description: 'Lead product design for our core platform experience.',
    requirements: ['5+ years design', 'Figma expert', 'User Research', 'Design Systems'],
    status: 'open',
    applicants: 12,
    postedDate: '2024-03-10',
  },
  {
    id: 'j4',
    title: 'DevOps Engineer',
    department: 'Infrastructure',
    location: 'Seattle, WA',
    type: 'full-time',
    salary: '₹150K - ₹180K',
    description: 'Build and maintain our cloud infrastructure.',
    requirements: ['AWS/GCP', 'Docker/K8s', 'CI/CD', 'IaC'],
    status: 'open',
    applicants: 9,
    postedDate: '2024-03-08',
  },
  {
    id: 'j5',
    title: 'Data Scientist',
    department: 'Data',
    location: 'Remote',
    type: 'full-time',
    salary: '₹155K - ₹185K',
    description: 'Drive data-informed decisions across the organization.',
    requirements: ['Python', 'Statistics', 'ML', 'Communication'],
    status: 'closed',
    applicants: 32,
    postedDate: '2024-02-15',
    closingDate: '2024-03-20',
  },
  {
    id: 'j6',
    title: 'Engineering Manager',
    department: 'Engineering',
    location: 'Boston, MA',
    type: 'full-time',
    salary: '₹200K - ₹250K',
    description: 'Lead and grow our platform engineering team.',
    requirements: ['8+ years experience', '3+ years management', 'Technical background'],
    status: 'open',
    applicants: 6,
    postedDate: '2024-03-12',
  },
];

export const clients: Client[] = [
  {
    id: 'cl1',
    name: 'TechVenture Solutions',
    industry: 'SaaS',
    logo: '',
    contactName: 'Michael Torres',
    contactEmail: 'michael@techventure.com',
    phone: '+1 (555) 111-2233',
    activeJobs: 4,
    totalPlacements: 12,
    status: 'active',
    createdAt: '2023-09-15',
  },
  {
    id: 'cl2',
    name: 'DataFlow Analytics',
    industry: 'Data & AI',
    logo: '',
    contactName: 'Lisa Park',
    contactEmail: 'lisa@dataflow.io',
    phone: '+1 (555) 222-3344',
    activeJobs: 2,
    totalPlacements: 8,
    status: 'active',
    createdAt: '2023-11-20',
  },
  {
    id: 'cl3',
    name: 'GreenScale Energy',
    industry: 'CleanTech',
    logo: '',
    contactName: 'Robert Chen',
    contactEmail: 'robert@greenscale.com',
    phone: '+1 (555) 333-4455',
    activeJobs: 3,
    totalPlacements: 5,
    status: 'active',
    createdAt: '2024-01-10',
  },
  {
    id: 'cl4',
    name: 'FinEdge Capital',
    industry: 'FinTech',
    logo: '',
    contactName: 'Amanda Richards',
    contactEmail: 'amanda@finedge.com',
    phone: '+1 (555) 444-5566',
    activeJobs: 1,
    totalPlacements: 3,
    status: 'prospect',
    createdAt: '2024-02-28',
  },
];

export const deals: Deal[] = [
  {
    id: 'd1',
    title: 'TechVenture - Engineering Team Expansion',
    clientId: 'cl1',
    value: 85000,
    stage: 'negotiation',
    probability: 75,
    assignedTo: 'u1',
    createdAt: '2024-03-01',
    expectedClose: '2024-04-15',
  },
  {
    id: 'd2',
    title: 'DataFlow - ML Team Build',
    clientId: 'cl2',
    value: 120000,
    stage: 'proposal',
    probability: 50,
    assignedTo: 'u1',
    createdAt: '2024-03-10',
    expectedClose: '2024-05-01',
  },
  {
    id: 'd3',
    title: 'GreenScale - CTO Search',
    clientId: 'cl3',
    value: 65000,
    stage: 'won',
    probability: 100,
    assignedTo: 'u1',
    createdAt: '2024-02-15',
    expectedClose: '2024-03-20',
  },
  {
    id: 'd4',
    title: 'FinEdge - Backend Engineers',
    clientId: 'cl4',
    value: 45000,
    stage: 'lead',
    probability: 20,
    assignedTo: 'u1',
    createdAt: '2024-03-18',
    expectedClose: '2024-06-01',
  },
];

export const activities: Activity[] = [
  {
    id: 'a1',
    type: 'ai_scoring',
    description: 'AI scored Alex Rivera at 94/100 for Senior Full-Stack Engineer',
    userId: 'system',
    timestamp: '2024-03-22T14:30:00Z',
  },
  {
    id: 'a2',
    type: 'status_change',
    description: 'Alex Rivera moved to Interview stage',
    userId: 'u1',
    timestamp: '2024-03-22T13:15:00Z',
  },
  {
    id: 'a3',
    type: 'interview_scheduled',
    description: 'Interview scheduled with Rachel Green for March 25',
    userId: 'u1',
    timestamp: '2024-03-22T11:00:00Z',
  },
  {
    id: 'a4',
    type: 'candidate_added',
    description: 'James Liu applied via Career Page',
    userId: 'system',
    timestamp: '2024-03-22T10:30:00Z',
  },
  {
    id: 'a5',
    type: 'note_added',
    description: 'Added note on Priya Patel: "Published 3 ML papers"',
    userId: 'u1',
    timestamp: '2024-03-21T16:45:00Z',
  },
  {
    id: 'a6',
    type: 'email_sent',
    description: 'Outreach email sent to David Kim',
    userId: 'u1',
    timestamp: '2024-03-21T15:00:00Z',
  },
  {
    id: 'a7',
    type: 'status_change',
    description: 'Emma Watson moved to Offer stage',
    userId: 'u1',
    timestamp: '2024-03-21T14:30:00Z',
  },
  {
    id: 'a8',
    type: 'ai_scoring',
    description: 'AI enrichment completed for 5 new candidates',
    userId: 'system',
    timestamp: '2024-03-21T12:00:00Z',
  },
];

export const notifications: Notification[] = [
  {
    id: 'n1',
    title: 'New Application',
    message: 'James Liu applied for Senior Full-Stack Engineer',
    type: 'info',
    read: false,
    timestamp: '2024-03-22T10:30:00Z',
    link: '/dashboard/candidates/c5',
  },
  {
    id: 'n2',
    title: 'AI Score Alert',
    message: 'Alex Rivera scored 94/100 — Top candidate match!',
    type: 'success',
    read: false,
    timestamp: '2024-03-22T14:30:00Z',
    link: '/dashboard/candidates/c1',
  },
  {
    id: 'n3',
    title: 'Interview Tomorrow',
    message: 'Rachel Green interview scheduled for 2:00 PM',
    type: 'warning',
    read: false,
    timestamp: '2024-03-22T09:00:00Z',
    link: '/dashboard/ats',
  },
  {
    id: 'n4',
    title: 'Offer Accepted',
    message: 'Sofia Martinez accepted the Data Scientist position',
    type: 'success',
    read: true,
    timestamp: '2024-03-21T16:00:00Z',
  },
];

export const analyticsData: AnalyticsData = {
  timeToHire: 28,
  totalCandidates: 156,
  openPositions: 5,
  placementRate: 68,
  activeRecruiters: 4,
  conversionRates: [
    { stage: 'Applied', rate: 100 },
    { stage: 'Screening', rate: 62 },
    { stage: 'Interview', rate: 38 },
    { stage: 'Offer', rate: 18 },
    { stage: 'Hired', rate: 12 },
  ],
  sourcePerformance: [
    { source: 'LinkedIn', count: 45, quality: 82 },
    { source: 'Referral', count: 28, quality: 90 },
    { source: 'Job Board', count: 38, quality: 65 },
    { source: 'Career Page', count: 32, quality: 72 },
    { source: 'Headhunting', count: 13, quality: 88 },
  ],
  weeklyApplications: [
    { week: 'W1', count: 23 },
    { week: 'W2', count: 31 },
    { week: 'W3', count: 28 },
    { week: 'W4', count: 42 },
    { week: 'W5', count: 35 },
    { week: 'W6', count: 48 },
    { week: 'W7', count: 39 },
    { week: 'W8', count: 52 },
  ],
  recruiterProductivity: [
    { name: 'Sarah Chen', placements: 12, interviews: 34 },
    { name: 'Mike Torres', placements: 9, interviews: 28 },
    { name: 'Lisa Park', placements: 7, interviews: 22 },
    { name: 'John Davis', placements: 5, interviews: 18 },
  ],
};

export const aiInsights: AIInsight[] = [
  {
    id: 'ai1',
    type: 'recommendation',
    title: 'Top Match Found',
    description: 'Alex Rivera is a 94% match for Senior Full-Stack Engineer. Schedule an interview now.',
    priority: 'high',
    actionLabel: 'Schedule Interview',
    actionLink: '/dashboard/ats',
  },
  {
    id: 'ai2',
    type: 'suggestion',
    title: 'Outreach Suggestion',
    description: 'Based on engagement data, Tuesday mornings see 40% higher response rates for outreach emails.',
    priority: 'medium',
  },
  {
    id: 'ai3',
    type: 'alert',
    title: 'Pipeline Bottleneck',
    description: 'Screening stage has 15 candidates waiting > 5 days. Consider additional screening sessions.',
    priority: 'high',
    actionLabel: 'View Pipeline',
    actionLink: '/dashboard/ats',
  },
  {
    id: 'ai4',
    type: 'recommendation',
    title: 'Skill Gap Detected',
    description: 'ML Engineer role has 0 candidates with MLOps experience. Consider expanding search criteria.',
    priority: 'medium',
    actionLabel: 'Edit Job',
    actionLink: '/dashboard/jobs',
  },
];

export const revenues: Revenue[] = [
  {
    id: 'rev1',
    amount: 250000,
    sourceType: 'placement',
    clientId: 'cl1',
    recruiterId: 'u1',
    jobId: 'j1',
    candidateId: 'c1',
    date: '2024-03-15',
    description: 'Placement fee for Senior Full-Stack Engineer',
    status: 'collected',
  },
  {
    id: 'rev2',
    amount: 180000,
    sourceType: 'placement',
    clientId: 'cl2',
    recruiterId: 'u2',
    jobId: 'j2',
    candidateId: 'c2',
    date: '2024-03-20',
    description: 'Placement fee for ML Engineer',
    status: 'pending',
  },
  {
    id: 'rev3',
    amount: 50000,
    sourceType: 'retainer',
    clientId: 'cl3',
    recruiterId: 'u1',
    date: '2024-03-01',
    description: 'Monthly Retainer - Q1',
    status: 'collected',
  },
];

export const expenses: Expense[] = [
  {
    id: 'exp1',
    category: 'salaries',
    amount: 450000,
    description: 'March Payroll',
    date: '2024-03-31',
  },
  {
    id: 'exp2',
    category: 'software',
    amount: 25000,
    description: 'LinkedIn Recruiter Subscription',
    date: '2024-03-05',
  },
  {
    id: 'exp3',
    category: 'marketing',
    amount: 15000,
    description: 'Google Ads - Recruitment Campaign',
    date: '2024-03-10',
  },
];

export const invoices: Invoice[] = [
  {
    id: 'INV-2024-001',
    clientId: 'cl1',
    amount: 250000,
    status: 'paid',
    dueDate: '2024-04-15',
    createdAt: '2024-03-15',
    items: [{ description: 'Placement Fee - Alex Rivera', amount: 250000 }],
  },
  {
    id: 'INV-2024-002',
    clientId: 'cl2',
    amount: 180000,
    status: 'pending',
    dueDate: '2024-04-20',
    createdAt: '2024-03-20',
    items: [{ description: 'Placement Fee - Priya Patel', amount: 180000 }],
  },
];

export const recruiterEarnings: RecruiterEarnings[] = [
  {
    recruiterId: 'u1',
    totalRevenue: 300000,
    commission: 45000,
    placementsCount: 12,
  },
  {
    recruiterId: 'u2',
    totalRevenue: 180000,
    commission: 27000,
    placementsCount: 9,
  },
];

export const financialStats: FinancialStats = {
  totalRevenue: 1250000,
  totalExpenses: 850000,
  netProfit: 400000,
  mrr: 150000,
  outstandingPayments: 280000,
  revenueThisMonth: 420000,
};
